import { normalizeAppLocale, type AppLocale } from "@/lib/app-locale"
import { getDoctorCopy } from "@/lib/doctor-copy"

const appCopy = {
  ru: {
    auth: {
      login: {
        title: "Вход",
        subtitle: "Войдите в свой аккаунт для доступа к платформе",
        emailLabel: "Email",
        passwordLabel: "Пароль",
        submit: "Войти",
        invalidCredentials: "Неверный email или пароль",
        genericError: "Произошла ошибка. Попробуйте снова.",
        decorativeCaption:
          "Платформа нового поколения для нейродиагностики с использованием искусственного интеллекта",
        passwordToggleShow: "Показать пароль",
        passwordToggleHide: "Скрыть пароль",
      },
    },
    doctorPatients: {
      pageTitle: "Пациенты",
      heading: "Мои пациенты",
      subtitle: "пациентов под наблюдением",
      searchPlaceholder: "Поиск пациента...",
      filter: "Фильтр",
      add: "Добавить",
      stats: {
        total: "Всего пациентов",
        active: "Активных",
        highRisk: "Высокий риск",
        newThisMonth: "Новых за месяц",
      },
      ageSuffix: "лет",
      analysesSuffix: "анализов",
      riskLabels: {
        low: "Низкий риск",
        moderate: "Средний риск",
        high: "Высокий риск",
      },
      lastVisit: {
        today: "Сегодня",
        yesterday: "Вчера",
        threeDaysAgo: "3 дня назад",
        weekAgo: "Неделю назад",
      },
    },
    doctorSettings: {
      pageTitle: "Настройки врача",
      heading: "Профиль и настройки",
      subtitle: "Базовые параметры аккаунта врача без дополнительных API-зависимостей.",
      profileSection: "Профиль аккаунта",
      notificationsSection: "Уведомления",
      fields: {
        name: "Имя",
        email: "Email",
        specialization: "Специализация",
        license: "Лицензия",
      },
      placeholders: {
        name: "Имя врача",
        email: "doctor@amanai.kz",
        specialization: "Специализация",
        license: "Номер лицензии",
        specializationValue: "Неврология",
        licenseValue: "Не указано",
      },
      rows: {
        emailAlerts: {
          title: "Email-оповещения",
          description: "Проверка новых анализов и отчётов.",
        },
        patientReminders: {
          title: "Напоминания по пациентам",
          description: "Плановые повторные осмотры и ожидающие ревью.",
        },
        security: {
          title: "Безопасность",
          description: "Пароль и дополнительные параметры будут подключены позже.",
        },
      },
      save: "Сохранить",
    },
    doctorDashboard: {
      pageTitle: "Панель врача",
      greeting: "Добрый день",
      doctorFallback: "Доктор",
      pendingSummary: "анализа(ов) на проверку",
      actions: {
        reviews: "Проверить анализы",
        patients: "Мои пациенты",
        reports: "Создать отчёт",
      },
      accuracy: {
        title: "Точность AI",
        description: "Подтверждённых диагнозов",
      },
      stats: {
        patients: { label: "Пациентов", description: "под наблюдением" },
        reviews: { label: "На проверку", description: "анализов AI" },
        reports: { label: "Отчётов", description: "создано" },
        visits: { label: "Приёмов", description: "на этой неделе" },
      },
      pendingReviews: {
        heading: "Ожидают проверки",
        all: "Все",
        empty: "Все анализы проверены",
        reviewTypes: {
          ctMri: "МРТ снимок",
          iot: "IoT сессия",
          questionnaire: "Опросник",
        },
      },
      recentPatients: {
        heading: "Недавние пациенты",
        all: "Все",
        analysesSuffix: "анализов",
        addPatient: "Добавить пациента",
      },
      timeLabels: {
        today: "Сегодня",
        yesterday: "Вчера",
        threeDaysAgo: "3 дня назад",
        twoHoursAgo: "2 часа назад",
        fiveHoursAgo: "5 часов назад",
      },
    },
    doctorReports: {
      pageTitle: "Отчёты пациентов",
      heading: "AI голосовые отчёты",
      subtitleSuffix: "отчётов",
      subtitleDescription: "Созданы из разговоров с голосовым помощником",
      searchPlaceholder: "Поиск...",
      emptyTitle: "Пока отчётов нет",
      emptyDescription: "Отчёты появятся после разговоров пациентов с голосовым помощником",
      listCountSuffix: "отчётов",
      anonymousPatient: "Анонимный пациент",
      anonymousShort: "Анонимный",
      duration: "Длительность",
      download: "Скачать",
      stats: {
        wellbeing: "Состояние",
        sleep: "Сон",
        mood: "Настроение",
        stress: "Стресс",
      },
      footer: "AI-сгенерированный отчёт • AMAN AI Platform",
      selectPrompt: "Выберите отчёт",
      fallbackSummaryTitle: "Заключение",
      riskLabels: {
        low: "Низкий",
        moderate: "Средний",
        high: "Высокий",
        critical: "Критический",
      },
      urgent: "Срочно",
      followup: "Нужно наблюдение",
      sectionTitles: {
        general: "Общее состояние",
        sleep: "Сон",
        mood: "Настроение",
        stress: "Стресс",
        symptoms: "Симптомы",
        conclusion: "Заключение",
        recommendations: "Рекомендации",
        other: "Информация",
      },
    },
    adminDashboard: {
      pageTitle: "Панель администратора",
      heading: "Администрирование платформы",
      subtitle: "Управление пользователями, сервисами и мониторинг системы",
      quickStats: {
        users: { label: "Пользователей", description: "всего" },
        analyses: { label: "Анализов", description: "за сегодня" },
        services: { label: "Сервисы", description: "активных" },
        status: { label: "Статус", description: "системы" },
      },
      usersByRole: "Пользователи по ролям",
      roleLabels: {
        patients: "Пациентов",
        doctors: "Врачей",
        admins: "Админов",
      },
      servicesStatus: "Статус сервисов",
      tableHeaders: {
        service: "Сервис",
        status: "Статус",
        url: "URL",
      },
      serviceStatuses: {
        active: "Активен",
        coming: "Скоро",
      },
      serviceNames: {
        questionnaire: "S3 - Опросники",
        genetics: "S4 - Генетика",
        blood: "S5 - Кровь",
        rehabilitation: "S6 - Реабилитация",
      },
    },
    adminStats: {
      pageTitle: "Статистика",
      heading: "Обзор статистики",
      subtitle: "Временный безопасный экран вместо 404 для административной навигации.",
      cards: {
        users: { label: "Пользователи", description: "лимит текущей выборки" },
        admins: { label: "Администраторы", description: "роль с полным доступом" },
        doctors: { label: "Врачи", description: "заполняется из пользовательского раздела" },
        activity: { label: "Активность", description: "базовый статус раздела" },
      },
    },
    adminUsers: {
      pageTitle: "Пользователи",
      heading: "Пользователи",
      subtitle: "Управление аккаунтами пациентов, врачей и администраторов",
      searchPlaceholder: "Поиск по имени, email, роли...",
      summary: {
        total: { label: "Всего", description: "аккаунтов" },
        doctors: { label: "Врачей", description: "в системе" },
        admins: { label: "Админов", description: "с доступом" },
      },
      tableHeaders: {
        user: "Пользователь",
        role: "Роль",
        details: "Детали",
        created: "Создан",
      },
      empty: {
        title: "Пользователи не найдены",
        description: "Измените запрос или проверьте данные в базе.",
      },
      roleLabels: {
        PATIENT: "Пациент",
        DOCTOR: "Врач",
        ADMIN: "Администратор",
      },
      defaultRows: {
        unnamed: "Без имени",
        doctorProfileMissing: "Профиль врача не заполнен",
        patientProfileMissing: "Профиль пациента не заполнен",
        systemAccess: "Системный доступ",
      },
    },
    adminSettings: {
      pageTitle: "Настройки администратора",
      heading: "Настройки доступа",
      subtitle: "Базовая страница настроек для административного раздела.",
      account: "Аккаунт",
      system: "Системные параметры",
      fields: {
        name: "Имя",
        email: "Email",
      },
      notices: {
        roles: "Управление ролями и аудит-логами будет вынесено в отдельный модуль.",
        alerts: "Оповещения о системных изменениях пока доступны как placeholder.",
      },
      save: "Сохранить",
    },
    adminServices: {
      pageTitle: "Сервисы",
      heading: "Каталог сервисов",
      subtitle: "Текущие сервисы платформы без изменения существующей интеграционной логики.",
      tableHeaders: {
        service: "Сервис",
        team: "Команда",
        status: "Статус",
        route: "Маршрут",
      },
      statuses: {
        active: "Активен",
        coming: "Скоро",
        maintenance: "Обслуживание",
      },
    },
    patientDashboard: {
      pageTitle: "Панель управления",
      welcomeLabel: "Добро пожаловать",
      welcomeSubtitle:
        "Начните с прохождения диагностики для получения персональных рекомендаций от AI",
      streak: "7 дней подряд",
      actions: {
        questionnaire: "Пройти опросник",
        uploadScan: "Загрузить снимок",
        iot: "IoT мониторинг",
      },
      score: {
        title: "Neuro-Readiness Score",
        sleep: "Сон",
        hrv: "HRV",
        stress: "Стресс",
      },
      stats: {
        analyses: { label: "Анализов", description: "всего проведено" },
        questionnaires: { label: "Опросников", description: "заполнено" },
        stress: { label: "Уровень стресса", description: "низкий" },
        nextVisit: { label: "Следующий визит", description: "декабря" },
      },
      services: {
        heading: "AI сервисы",
        availableSuffix: "доступно",
      },
      recommendations: {
        heading: "AI Рекомендации",
        items: {
          heart: { title: "Проверьте сердечный ритм", description: "Рекомендуем IoT мониторинг" },
          cognition: { title: "Когнитивный тест", description: "Пройдите опросник MMSE" },
          stress: { title: "Уровень стресса", description: "Оценка через PSS-10" },
        },
      },
      tasks: {
        heading: "Задачи",
        items: {
          profile: "Заполнить профиль",
          questionnaire: "Пройти первый опросник",
          iot: "Подключить IoT устройство",
        },
      },
      recentActivity: {
        heading: "Последняя активность",
        allHistory: "Вся история",
        items: {
          mri: {
            title: "MRI анализ завершён",
            description: "Патологий не обнаружено",
            time: "2 часа назад",
          },
          pss: {
            title: "Опросник PSS-10",
            description: "Уровень стресса: низкий",
            time: "Вчера",
          },
          iot: {
            title: "IoT синхронизация",
            description: "Данные за 7 дней загружены",
            time: "2 дня назад",
          },
        },
      },
      healthInsights: {
        heading: "Показатели здоровья",
        period: "За неделю",
        stressLabel: "Стресс",
      },
    },
    patientSettings: {
      pageTitle: "Настройки",
      tabs: {
        notifications: "Уведомления",
        security: "Безопасность",
        appearance: "Внешний вид",
        language: "Язык",
        devices: "Устройства",
      },
      dangerZone: {
        title: "Опасная зона",
        signOut: "Выйти из аккаунта",
      },
      notifications: {
        title: "Уведомления",
        email: { title: "Email уведомления", description: "Получать уведомления на почту" },
        push: { title: "Push уведомления", description: "Уведомления в браузере" },
        results: { title: "Результаты анализов", description: "Когда готовы результаты AI-анализа" },
        reminders: { title: "Напоминания", description: "О предстоящих визитах и обследованиях" },
      },
      security: {
        title: "Безопасность",
        email: "Email",
        password: "Пароль",
        change: "Изменить",
        currentPassword: "Текущий пароль",
        newPassword: "Новый пароль",
        save: "Сохранить",
        twoFactorTitle: "Двухфакторная аутентификация",
        twoFactorDescription: "Дополнительная защита аккаунта",
        configure: "Настроить",
        deleteTitle: "Удаление аккаунта",
        deleteDescription: "После удаления аккаунта все ваши данные будут безвозвратно удалены.",
        deleteAction: "Удалить аккаунт",
        showPassword: "Показать пароль",
        hidePassword: "Скрыть пароль",
      },
      appearance: {
        title: "Внешний вид",
        theme: "Тема",
        light: "Светлая",
        dark: "Тёмная",
        system: "Системная",
      },
      language: {
        title: "Язык",
      },
      devices: {
        title: "Подключённые устройства",
        currentDevice: "Текущее устройство",
        currentDeviceMeta: "Windows • Chrome • Актуально",
        active: "Активно",
        empty: "Нет других подключённых устройств",
      },
    },
  },
  en: {
    auth: {
      login: {
        title: "Sign in",
        subtitle: "Sign in to your account to access the platform",
        emailLabel: "Email",
        passwordLabel: "Password",
        submit: "Sign in",
        invalidCredentials: "Invalid email or password",
        genericError: "Something went wrong. Please try again.",
        decorativeCaption: "A next-generation neurodiagnostics platform powered by artificial intelligence",
        passwordToggleShow: "Show password",
        passwordToggleHide: "Hide password",
      },
    },
    doctorPatients: {
      pageTitle: "Patients",
      heading: "My patients",
      subtitle: "patients under observation",
      searchPlaceholder: "Search patients...",
      filter: "Filter",
      add: "Add",
      stats: {
        total: "Total patients",
        active: "Active",
        highRisk: "High risk",
        newThisMonth: "New this month",
      },
      ageSuffix: "years old",
      analysesSuffix: "analyses",
      riskLabels: {
        low: "Low risk",
        moderate: "Moderate risk",
        high: "High risk",
      },
      lastVisit: {
        today: "Today",
        yesterday: "Yesterday",
        threeDaysAgo: "3 days ago",
        weekAgo: "A week ago",
      },
    },
    doctorSettings: {
      pageTitle: "Doctor settings",
      heading: "Profile and settings",
      subtitle: "Baseline doctor account settings without additional API dependencies.",
      profileSection: "Account profile",
      notificationsSection: "Notifications",
      fields: {
        name: "Name",
        email: "Email",
        specialization: "Specialization",
        license: "License",
      },
      placeholders: {
        name: "Doctor name",
        email: "doctor@amanai.kz",
        specialization: "Specialization",
        license: "License number",
        specializationValue: "Neurology",
        licenseValue: "Not specified",
      },
      rows: {
        emailAlerts: {
          title: "Email alerts",
          description: "Updates for new analyses and reports.",
        },
        patientReminders: {
          title: "Patient reminders",
          description: "Scheduled follow-ups and pending reviews.",
        },
        security: {
          title: "Security",
          description: "Password and advanced options will be connected later.",
        },
      },
      save: "Save",
    },
    doctorDashboard: {
      pageTitle: "Doctor dashboard",
      greeting: "Good day",
      doctorFallback: "Doctor",
      pendingSummary: "analysis review(s) pending",
      actions: {
        reviews: "Review analyses",
        patients: "My patients",
        reports: "Create report",
      },
      accuracy: {
        title: "AI accuracy",
        description: "Confirmed diagnoses",
      },
      stats: {
        patients: { label: "Patients", description: "under care" },
        reviews: { label: "In review", description: "AI analyses" },
        reports: { label: "Reports", description: "created" },
        visits: { label: "Visits", description: "this week" },
      },
      pendingReviews: {
        heading: "Pending review",
        all: "All",
        empty: "All analyses reviewed",
        reviewTypes: {
          ctMri: "MRI scan",
          iot: "IoT session",
          questionnaire: "Questionnaire",
        },
      },
      recentPatients: {
        heading: "Recent patients",
        all: "All",
        analysesSuffix: "analyses",
        addPatient: "Add patient",
      },
      timeLabels: {
        today: "Today",
        yesterday: "Yesterday",
        threeDaysAgo: "3 days ago",
        twoHoursAgo: "2 hours ago",
        fiveHoursAgo: "5 hours ago",
      },
    },
    doctorReports: {
      pageTitle: "Patient reports",
      heading: "AI voice reports",
      subtitleSuffix: "reports",
      subtitleDescription: "Generated from voice assistant conversations",
      searchPlaceholder: "Search...",
      emptyTitle: "No reports yet",
      emptyDescription: "Reports will appear after patients talk to the voice assistant",
      listCountSuffix: "reports",
      anonymousPatient: "Anonymous patient",
      anonymousShort: "Anonymous",
      duration: "Duration",
      download: "Download",
      stats: {
        wellbeing: "Condition",
        sleep: "Sleep",
        mood: "Mood",
        stress: "Stress",
      },
      footer: "AI-generated report • AMAN AI Platform",
      selectPrompt: "Select a report",
      fallbackSummaryTitle: "Conclusion",
      riskLabels: {
        low: "Low",
        moderate: "Moderate",
        high: "High",
        critical: "Critical",
      },
      urgent: "Urgent",
      followup: "Follow-up needed",
      sectionTitles: {
        general: "General condition",
        sleep: "Sleep",
        mood: "Mood",
        stress: "Stress",
        symptoms: "Symptoms",
        conclusion: "Conclusion",
        recommendations: "Recommendations",
        other: "Information",
      },
    },
    adminDashboard: {
      pageTitle: "Admin dashboard",
      heading: "Platform administration",
      subtitle: "Manage users, services, and system monitoring",
      quickStats: {
        users: { label: "Users", description: "total" },
        analyses: { label: "Analyses", description: "today" },
        services: { label: "Services", description: "active" },
        status: { label: "Status", description: "system" },
      },
      usersByRole: "Users by role",
      roleLabels: {
        patients: "Patients",
        doctors: "Doctors",
        admins: "Admins",
      },
      servicesStatus: "Service status",
      tableHeaders: {
        service: "Service",
        status: "Status",
        url: "URL",
      },
      serviceStatuses: {
        active: "Active",
        coming: "Coming soon",
      },
      serviceNames: {
        questionnaire: "S3 - Questionnaires",
        genetics: "S4 - Genetics",
        blood: "S5 - Blood",
        rehabilitation: "S6 - Rehabilitation",
      },
    },
    adminStats: {
      pageTitle: "Statistics",
      heading: "Statistics overview",
      subtitle: "Temporary safe screen for admin navigation instead of a 404.",
      cards: {
        users: { label: "Users", description: "current query limit" },
        admins: { label: "Administrators", description: "full-access role" },
        doctors: { label: "Doctors", description: "populated from the user area" },
        activity: { label: "Activity", description: "baseline section status" },
      },
    },
    adminUsers: {
      pageTitle: "Users",
      heading: "Users",
      subtitle: "Manage patient, doctor, and administrator accounts",
      searchPlaceholder: "Search by name, email, role...",
      summary: {
        total: { label: "Total", description: "accounts" },
        doctors: { label: "Doctors", description: "in system" },
        admins: { label: "Admins", description: "with access" },
      },
      tableHeaders: {
        user: "User",
        role: "Role",
        details: "Details",
        created: "Created",
      },
      empty: {
        title: "No users found",
        description: "Adjust the query or verify the database records.",
      },
      roleLabels: {
        PATIENT: "Patient",
        DOCTOR: "Doctor",
        ADMIN: "Administrator",
      },
      defaultRows: {
        unnamed: "Unnamed",
        doctorProfileMissing: "Doctor profile is incomplete",
        patientProfileMissing: "Patient profile is incomplete",
        systemAccess: "System access",
      },
    },
    adminSettings: {
      pageTitle: "Admin settings",
      heading: "Access settings",
      subtitle: "Baseline settings page for the administrative area.",
      account: "Account",
      system: "System settings",
      fields: {
        name: "Name",
        email: "Email",
      },
      notices: {
        roles: "Role management and audit logs will move to a separate module.",
        alerts: "System change alerts are still available as a placeholder.",
      },
      save: "Save",
    },
    adminServices: {
      pageTitle: "Services",
      heading: "Service catalog",
      subtitle: "Current platform services without changing existing integration logic.",
      tableHeaders: {
        service: "Service",
        team: "Team",
        status: "Status",
        route: "Route",
      },
      statuses: {
        active: "Active",
        coming: "Coming soon",
        maintenance: "Maintenance",
      },
    },
    patientDashboard: {
      pageTitle: "Dashboard",
      welcomeLabel: "Welcome",
      welcomeSubtitle: "Start with a diagnostic flow to receive AI-powered personalized guidance",
      streak: "7 days in a row",
      actions: {
        questionnaire: "Take questionnaire",
        uploadScan: "Upload scan",
        iot: "IoT monitoring",
      },
      score: {
        title: "Neuro-Readiness Score",
        sleep: "Sleep",
        hrv: "HRV",
        stress: "Stress",
      },
      stats: {
        analyses: { label: "Analyses", description: "completed total" },
        questionnaires: { label: "Questionnaires", description: "completed" },
        stress: { label: "Stress level", description: "low" },
        nextVisit: { label: "Next visit", description: "December" },
      },
      services: {
        heading: "AI services",
        availableSuffix: "available",
      },
      recommendations: {
        heading: "AI recommendations",
        items: {
          heart: { title: "Check your heart rhythm", description: "We recommend IoT monitoring" },
          cognition: { title: "Cognitive test", description: "Take the MMSE questionnaire" },
          stress: { title: "Stress level", description: "Assess with PSS-10" },
        },
      },
      tasks: {
        heading: "Tasks",
        items: {
          profile: "Complete your profile",
          questionnaire: "Take your first questionnaire",
          iot: "Connect an IoT device",
        },
      },
      recentActivity: {
        heading: "Recent activity",
        allHistory: "Full history",
        items: {
          mri: {
            title: "MRI analysis completed",
            description: "No pathology detected",
            time: "2 hours ago",
          },
          pss: {
            title: "PSS-10 questionnaire",
            description: "Stress level: low",
            time: "Yesterday",
          },
          iot: {
            title: "IoT sync",
            description: "Loaded 7 days of data",
            time: "2 days ago",
          },
        },
      },
      healthInsights: {
        heading: "Health insights",
        period: "This week",
        stressLabel: "Stress",
      },
    },
    patientSettings: {
      pageTitle: "Settings",
      tabs: {
        notifications: "Notifications",
        security: "Security",
        appearance: "Appearance",
        language: "Language",
        devices: "Devices",
      },
      dangerZone: {
        title: "Danger zone",
        signOut: "Sign out",
      },
      notifications: {
        title: "Notifications",
        email: { title: "Email notifications", description: "Receive updates by email" },
        push: { title: "Push notifications", description: "Browser notifications" },
        results: { title: "Analysis results", description: "When AI analysis results are ready" },
        reminders: { title: "Reminders", description: "Upcoming visits and examinations" },
      },
      security: {
        title: "Security",
        email: "Email",
        password: "Password",
        change: "Change",
        currentPassword: "Current password",
        newPassword: "New password",
        save: "Save",
        twoFactorTitle: "Two-factor authentication",
        twoFactorDescription: "Additional account protection",
        configure: "Configure",
        deleteTitle: "Delete account",
        deleteDescription: "Deleting your account permanently removes all of your data.",
        deleteAction: "Delete account",
        showPassword: "Show password",
        hidePassword: "Hide password",
      },
      appearance: {
        title: "Appearance",
        theme: "Theme",
        light: "Light",
        dark: "Dark",
        system: "System",
      },
      language: {
        title: "Language",
      },
      devices: {
        title: "Connected devices",
        currentDevice: "Current device",
        currentDeviceMeta: "Windows • Chrome • Current",
        active: "Active",
        empty: "No other connected devices",
      },
    },
  },
  kk: {
    auth: {
      login: {
        title: "Кіру",
        subtitle: "Платформаға қол жеткізу үшін аккаунтыңызға кіріңіз",
        emailLabel: "Email",
        passwordLabel: "Құпиясөз",
        submit: "Кіру",
        invalidCredentials: "Email немесе құпиясөз қате",
        genericError: "Қате орын алды. Қайталап көріңіз.",
        decorativeCaption:
          "Жасанды интеллект негізіндегі жаңа буын нейродиагностика платформасы",
        passwordToggleShow: "Құпиясөзді көрсету",
        passwordToggleHide: "Құпиясөзді жасыру",
      },
    },
    doctorPatients: {
      pageTitle: "Пациенттер",
      heading: "Менің пациенттерім",
      subtitle: "бақылаудағы пациент",
      searchPlaceholder: "Пациентті іздеу...",
      filter: "Сүзгі",
      add: "Қосу",
      stats: {
        total: "Барлық пациент",
        active: "Белсенді",
        highRisk: "Жоғары тәуекел",
        newThisMonth: "Осы айдағы жаңа",
      },
      ageSuffix: "жас",
      analysesSuffix: "талдау",
      riskLabels: {
        low: "Төмен тәуекел",
        moderate: "Орташа тәуекел",
        high: "Жоғары тәуекел",
      },
      lastVisit: {
        today: "Бүгін",
        yesterday: "Кеше",
        threeDaysAgo: "3 күн бұрын",
        weekAgo: "Бір апта бұрын",
      },
    },
    doctorSettings: {
      pageTitle: "Дәрігер баптаулары",
      heading: "Профиль және баптаулар",
      subtitle: "Қосымша API тәуелділіктерінсіз дәрігер аккаунтының негізгі параметрлері.",
      profileSection: "Аккаунт профилі",
      notificationsSection: "Хабарламалар",
      fields: {
        name: "Аты",
        email: "Email",
        specialization: "Мамандану",
        license: "Лицензия",
      },
      placeholders: {
        name: "Дәрігердің аты",
        email: "doctor@amanai.kz",
        specialization: "Мамандану",
        license: "Лицензия нөмірі",
        specializationValue: "Неврология",
        licenseValue: "Көрсетілмеген",
      },
      rows: {
        emailAlerts: {
          title: "Email хабарламалары",
          description: "Жаңа талдаулар мен есептер туралы жаңартулар.",
        },
        patientReminders: {
          title: "Пациент еске салғыштары",
          description: "Жоспарлы бақылаулар мен күтілетін ревьюлер.",
        },
        security: {
          title: "Қауіпсіздік",
          description: "Құпиясөз және қосымша параметрлер кейінірек қосылады.",
        },
      },
      save: "Сақтау",
    },
    doctorDashboard: {
      pageTitle: "Дәрігер панелі",
      greeting: "Қайырлы күн",
      doctorFallback: "Дәрігер",
      pendingSummary: "талдау тексеруді күтуде",
      actions: {
        reviews: "Талдауларды тексеру",
        patients: "Менің пациенттерім",
        reports: "Есеп құру",
      },
      accuracy: {
        title: "AI дәлдігі",
        description: "Расталған диагноздар",
      },
      stats: {
        patients: { label: "Пациенттер", description: "бақылауда" },
        reviews: { label: "Тексеруде", description: "AI талдаулар" },
        reports: { label: "Есептер", description: "құрылды" },
        visits: { label: "Қабылдаулар", description: "осы аптада" },
      },
      pendingReviews: {
        heading: "Тексеруді күтуде",
        all: "Барлығы",
        empty: "Барлық талдаулар тексерілді",
        reviewTypes: {
          ctMri: "МРТ суреті",
          iot: "IoT сессиясы",
          questionnaire: "Сауалнама",
        },
      },
      recentPatients: {
        heading: "Соңғы пациенттер",
        all: "Барлығы",
        analysesSuffix: "талдау",
        addPatient: "Пациент қосу",
      },
      timeLabels: {
        today: "Бүгін",
        yesterday: "Кеше",
        threeDaysAgo: "3 күн бұрын",
        twoHoursAgo: "2 сағат бұрын",
        fiveHoursAgo: "5 сағат бұрын",
      },
    },
    doctorReports: {
      pageTitle: "Пациент есептері",
      heading: "AI дауыстық есептері",
      subtitleSuffix: "есеп",
      subtitleDescription: "Дауыстық көмекшімен сөйлесулерден жасалған",
      searchPlaceholder: "Іздеу...",
      emptyTitle: "Әзірше есептер жоқ",
      emptyDescription: "Пациенттер дауыстық көмекшімен сөйлескеннен кейін есептер пайда болады",
      listCountSuffix: "есеп",
      anonymousPatient: "Анонимді пациент",
      anonymousShort: "Анонимді",
      duration: "Ұзақтығы",
      download: "Жүктеу",
      stats: {
        wellbeing: "Жағдай",
        sleep: "Ұйқы",
        mood: "Көңіл-күй",
        stress: "Стресс",
      },
      footer: "AI жасаған есеп • AMAN AI Platform",
      selectPrompt: "Есепті таңдаңыз",
      fallbackSummaryTitle: "Қорытынды",
      riskLabels: {
        low: "Төмен",
        moderate: "Орташа",
        high: "Жоғары",
        critical: "Қауіпті",
      },
      urgent: "Шұғыл",
      followup: "Бақылау қажет",
      sectionTitles: {
        general: "Жалпы жағдай",
        sleep: "Ұйқы",
        mood: "Көңіл-күй",
        stress: "Стресс",
        symptoms: "Симптомдар",
        conclusion: "Қорытынды",
        recommendations: "Ұсыныстар",
        other: "Ақпарат",
      },
    },
    adminDashboard: {
      pageTitle: "Әкімші панелі",
      heading: "Платформаны басқару",
      subtitle: "Пайдаланушыларды, сервистерді және жүйе мониторингін басқару",
      quickStats: {
        users: { label: "Пайдаланушылар", description: "барлығы" },
        analyses: { label: "Талдаулар", description: "бүгін" },
        services: { label: "Сервистер", description: "белсенді" },
        status: { label: "Күй", description: "жүйе" },
      },
      usersByRole: "Рөлдер бойынша пайдаланушылар",
      roleLabels: {
        patients: "Пациенттер",
        doctors: "Дәрігерлер",
        admins: "Әкімшілер",
      },
      servicesStatus: "Сервис күйі",
      tableHeaders: {
        service: "Сервис",
        status: "Күй",
        url: "URL",
      },
      serviceStatuses: {
        active: "Белсенді",
        coming: "Жақында",
      },
      serviceNames: {
        questionnaire: "S3 - Сауалнамалар",
        genetics: "S4 - Генетика",
        blood: "S5 - Қан",
        rehabilitation: "S6 - Оңалту",
      },
    },
    adminStats: {
      pageTitle: "Статистика",
      heading: "Статистикаға шолу",
      subtitle: "Әкімшілік навигация үшін 404 орнына уақытша қауіпсіз экран.",
      cards: {
        users: { label: "Пайдаланушылар", description: "ағымдағы іріктеу лимиті" },
        admins: { label: "Әкімшілер", description: "толық қолжетімді рөл" },
        doctors: { label: "Дәрігерлер", description: "пайдаланушы бөлімінен толтырылады" },
        activity: { label: "Белсенділік", description: "бөлімнің базалық күйі" },
      },
    },
    adminUsers: {
      pageTitle: "Пайдаланушылар",
      heading: "Пайдаланушылар",
      subtitle: "Пациент, дәрігер және әкімші аккаунттарын басқару",
      searchPlaceholder: "Аты, email, рөлі бойынша іздеу...",
      summary: {
        total: { label: "Барлығы", description: "аккаунт" },
        doctors: { label: "Дәрігерлер", description: "жүйеде" },
        admins: { label: "Әкімшілер", description: "қолжетімділікпен" },
      },
      tableHeaders: {
        user: "Пайдаланушы",
        role: "Рөл",
        details: "Детальдар",
        created: "Құрылды",
      },
      empty: {
        title: "Пайдаланушылар табылмады",
        description: "Сұрауды өзгертіңіз немесе дерекқор жазбаларын тексеріңіз.",
      },
      roleLabels: {
        PATIENT: "Пациент",
        DOCTOR: "Дәрігер",
        ADMIN: "Әкімші",
      },
      defaultRows: {
        unnamed: "Аты жоқ",
        doctorProfileMissing: "Дәрігер профилі толтырылмаған",
        patientProfileMissing: "Пациент профилі толтырылмаған",
        systemAccess: "Жүйелік қолжетім",
      },
    },
    adminSettings: {
      pageTitle: "Әкімші баптаулары",
      heading: "Қолжетім баптаулары",
      subtitle: "Әкімшілік бөлімге арналған негізгі баптаулар беті.",
      account: "Аккаунт",
      system: "Жүйелік параметрлер",
      fields: {
        name: "Аты",
        email: "Email",
      },
      notices: {
        roles: "Рөлдерді басқару және аудит журналдары бөлек модульге шығарылады.",
        alerts: "Жүйелік өзгерістер туралы хабарламалар әзірге placeholder ретінде қолжетімді.",
      },
      save: "Сақтау",
    },
    adminServices: {
      pageTitle: "Сервистер",
      heading: "Сервис каталогы",
      subtitle: "Қолданыстағы интеграция логикасын өзгертпей платформаның ағымдағы сервистері.",
      tableHeaders: {
        service: "Сервис",
        team: "Команда",
        status: "Күй",
        route: "Маршрут",
      },
      statuses: {
        active: "Белсенді",
        coming: "Жақында",
        maintenance: "Қызмет көрсету",
      },
    },
    patientDashboard: {
      pageTitle: "Басты бет",
      welcomeLabel: "Қош келдіңіз",
      welcomeSubtitle: "AI ұсынатын жеке ұсыныстарды алу үшін диагностикадан бастаңыз",
      streak: "7 күн қатарынан",
      actions: {
        questionnaire: "Сауалнамадан өту",
        uploadScan: "Суретті жүктеу",
        iot: "IoT мониторингі",
      },
      score: {
        title: "Neuro-Readiness Score",
        sleep: "Ұйқы",
        hrv: "HRV",
        stress: "Стресс",
      },
      stats: {
        analyses: { label: "Талдаулар", description: "барлығы орындалды" },
        questionnaires: { label: "Сауалнамалар", description: "толтырылды" },
        stress: { label: "Стресс деңгейі", description: "төмен" },
        nextVisit: { label: "Келесі қабылдау", description: "желтоқсан" },
      },
      services: {
        heading: "AI сервистері",
        availableSuffix: "қолжетімді",
      },
      recommendations: {
        heading: "AI ұсыныстары",
        items: {
          heart: { title: "Жүрек ырғағын тексеріңіз", description: "IoT мониторингін ұсынамыз" },
          cognition: { title: "Когнитивтік тест", description: "MMSE сауалнамасын өтіңіз" },
          stress: { title: "Стресс деңгейі", description: "PSS-10 арқылы бағалау" },
        },
      },
      tasks: {
        heading: "Тапсырмалар",
        items: {
          profile: "Профильді толтыру",
          questionnaire: "Алғашқы сауалнамадан өту",
          iot: "IoT құрылғысын қосу",
        },
      },
      recentActivity: {
        heading: "Соңғы белсенділік",
        allHistory: "Барлық тарих",
        items: {
          mri: {
            title: "MRI талдауы аяқталды",
            description: "Патология анықталмады",
            time: "2 сағат бұрын",
          },
          pss: {
            title: "PSS-10 сауалнамасы",
            description: "Стресс деңгейі: төмен",
            time: "Кеше",
          },
          iot: {
            title: "IoT синхрондау",
            description: "7 күндік деректер жүктелді",
            time: "2 күн бұрын",
          },
        },
      },
      healthInsights: {
        heading: "Денсаулық көрсеткіштері",
        period: "Осы апта",
        stressLabel: "Стресс",
      },
    },
    patientSettings: {
      pageTitle: "Баптаулар",
      tabs: {
        notifications: "Хабарламалар",
        security: "Қауіпсіздік",
        appearance: "Сыртқы көрініс",
        language: "Тіл",
        devices: "Құрылғылар",
      },
      dangerZone: {
        title: "Қауіпті аймақ",
        signOut: "Аккаунттан шығу",
      },
      notifications: {
        title: "Хабарламалар",
        email: { title: "Email хабарламалары", description: "Email арқылы жаңартулар алу" },
        push: { title: "Push хабарламалары", description: "Браузер хабарламалары" },
        results: { title: "Талдау нәтижелері", description: "AI нәтижелері дайын болғанда" },
        reminders: { title: "Еске салғыштар", description: "Алдағы қабылдаулар мен тексерулер" },
      },
      security: {
        title: "Қауіпсіздік",
        email: "Email",
        password: "Құпиясөз",
        change: "Өзгерту",
        currentPassword: "Ағымдағы құпиясөз",
        newPassword: "Жаңа құпиясөз",
        save: "Сақтау",
        twoFactorTitle: "Екі факторлы аутентификация",
        twoFactorDescription: "Аккаунтты қосымша қорғау",
        configure: "Баптау",
        deleteTitle: "Аккаунтты жою",
        deleteDescription: "Аккаунт жойылғаннан кейін барлық деректеріңіз біржола өшіріледі.",
        deleteAction: "Аккаунтты жою",
        showPassword: "Құпиясөзді көрсету",
        hidePassword: "Құпиясөзді жасыру",
      },
      appearance: {
        title: "Сыртқы көрініс",
        theme: "Тақырып",
        light: "Жарық",
        dark: "Қараңғы",
        system: "Жүйелік",
      },
      language: {
        title: "Тіл",
      },
      devices: {
        title: "Қосылған құрылғылар",
        currentDevice: "Ағымдағы құрылғы",
        currentDeviceMeta: "Windows • Chrome • Ағымдағы",
        active: "Белсенді",
        empty: "Басқа қосылған құрылғылар жоқ",
      },
    },
  },
} as const

export function getAppCopy(localeLike?: string | null) {
  const locale = normalizeAppLocale(localeLike)

  return {
    ...getDoctorCopy(locale),
    ...appCopy[locale],
  }
}

export type AppCopy = ReturnType<typeof getAppCopy>
export type AppCopyLocale = AppLocale
