export const services = [
  // MRI Analysis Services
  {
    id: "mri-classification",
    title: "MRI Классификация",
    description: "Deep Learning классификация МРТ снимков",
    longDescription: "Deep Learning классификация МРТ изображений для диагностики нейродегенеративных заболеваний",
    iconName: "ScanLine",
    href: "/dashboard/mri-classification",
    embedUrl: "https://classification.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "mri-seg-static",
    title: "MRI Сегментация (Static)",
    description: "Статическая сегментация МРТ снимков",
    longDescription: "Сегментация областей мозга для выявления патологий",
    iconName: "BrainCircuit",
    href: "/dashboard/mri-seg-static",
    embedUrl: "https://seg-stat.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "mri-seg-adaptive",
    title: "MRI Сегментация (Adaptive)",
    description: "Адаптивная сегментация МРТ снимков",
    longDescription: "Адаптивная сегментация с постоянным улучшением модели",
    iconName: "Brain",
    href: "/dashboard/mri-seg-adaptive",
    embedUrl: "https://seg-adap.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "ml-static",
    title: "ML Анализ (Static)",
    description: "Статический ML анализ данных",
    longDescription: "Машинное обучение для анализа медицинских данных",
    iconName: "FlaskConical",
    href: "/dashboard/ml-static",
    embedUrl: "https://ml-stat.aman-ai.kz",
    team: ["Adilet"],
    status: "active" as const,
  },
  {
    id: "ml-adaptive",
    title: "ML Анализ (Adaptive)",
    description: "Адаптивный ML анализ данных",
    longDescription: "Адаптивное машинное обучение с автоматической донастройкой",
    iconName: "TestTube2",
    href: "/dashboard/ml-adaptive",
    embedUrl: "https://ml-adap.aman-ai.kz",
    team: ["Adilet"],
    status: "active" as const,
  },
  // IoT & Questionnaire
  {
    id: "iot",
    title: "IoT Мониторинг",
    description: "Мониторинг показателей здоровья в реальном времени",
    longDescription: "PPG, IMU, EMG сенсоры для мониторинга стресса и состояния нервной системы",
    iconName: "Waves",
    href: "/dashboard/iot",
    embedUrl: "https://dev.amanai.com.kz",
    team: ["Mukhammedzhan"],
    status: "active" as const,
  },
  {
    id: "questionnaire",
    title: "Анамнез жизни",
    description: "Сбор и анализ истории болезни пациента",
    longDescription: "AI-анализ анамнеза для оценки факторов риска и персонализированной диагностики",
    iconName: "ClipboardList",
    href: "/dashboard/questionnaire",
    embedUrl: null,
    team: ["Mukhammedzhan"],
    status: "active" as const,
  },
  {
    id: "cv-analysis",
    title: "CV Анализ",
    description: "Computer Vision анализ движений",
    longDescription: "Анализ движений и поз с помощью компьютерного зрения",
    iconName: "PersonStanding",
    href: "/dashboard/cv-analysis",
    embedUrl: "https://cv.amanai.com.kz",
    team: ["Mukhammedzhan"],
    status: "active" as const,
  },
  // Genetics & Blood
  {
    id: "genetics",
    title: "Генетический анализ",
    description: "Анализ генетических данных для диагностики",
    longDescription: "AlphaFold и ESMFold для анализа генетических данных и прогнозирования структуры белков",
    iconName: "Dna",
    href: "/dashboard/genetics",
    embedUrl: null,
    team: ["Samiullah", "Alnur"],
    status: "active" as const,
  },
  {
    id: "alphafold",
    title: "AlphaFold Server",
    description: "3D структура белков от DeepMind",
    longDescription: "Официальный AlphaFold Server для предсказания 3D структуры белков по аминокислотной последовательности",
    iconName: "Atom",
    href: "/dashboard/alphafold",
    embedUrl: null,
    externalUrl: "https://alphafoldserver.com",
    team: ["Alnur"],
    status: "active" as const,
  },
  {
    id: "blood",
    title: "Анализ крови",
    description: "Интерпретация результатов анализа крови",
    longDescription: "ML-анализ показателей крови для выявления биомаркеров нейродегенеративных заболеваний",
    iconName: "Syringe",
    href: "/dashboard/blood",
    embedUrl: null,
    team: ["Samiullah", "Alnur"],
    status: "active" as const,
  },
  // Rehabilitation
  {
    id: "rehabilitation",
    title: "Реабилитация",
    description: "Персонализированные программы восстановления",
    longDescription: "YOLO и Computer Vision для отслеживания движений и персонализированной нейрореабилитации",
    iconName: "Dumbbell",
    href: "/dashboard/rehabilitation",
    embedUrl: null,
    team: ["Murat", "Adilet"],
    status: "active" as const,
  },
  // Library
  {
    id: "library",
    title: "Библиотека",
    description: "Образовательные и релаксационные материалы",
    longDescription: "Видео, аудио и статьи для обучения, релаксации и улучшения сна",
    iconName: "BookOpen",
    href: "/dashboard/library",
    embedUrl: null,
    team: ["Alnur"],
    status: "active" as const,
  },
]

export type Service = typeof services[number]
export type ServiceStatus = "active" | "coming" | "maintenance"

